name: Release
on:
  push:
    tags: ["*"]
env:
  PLUGIN_NAME: table-editor-obsidian
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install modules
        run: npm ci

      - name: Run build
        run: npm run build

      - name: Package
        run: |
          mkdir ${{ env.PLUGIN_NAME }}
          cp main.js manifest.json styles.css ${{ env.PLUGIN_NAME }}
          zip -r ${{ env.PLUGIN_NAME }}.zip ${{ env.PLUGIN_NAME }}

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          prerelease: false
          files: |
            ${{ env.PLUGIN_NAME }}.zip
            main.js
            manifest.json
            styles.css
